services:
  db:
    image: ankane/pgvector:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: loomi
      POSTGRES_PASSWORD: S3nhL00m1!
      POSTGRES_DB: tintas
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suvinil_api
    restart: on-failure
    depends_on:
      - db
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgres://loomi:S3nhL00m1!@db:5432/tintas
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  db_data: {}